[package]
name = "hello_world"
version = "0.0.0"
edition = "2018"
publish = false

[dependencies]
rocket = "0.4"
serde = "*"
rocket_contrib = "0.4"
okapi = "0.3"
schemars = "0.6"
rocket_okapi = "0.3"

